[env:m5stack-cardputer-adv]
platform = espressif32
board = m5stack-cardputer-adv
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
lib_deps =
  m5stack/M5Cardputer @ ^1.0.2
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
