name: Build CalcPuter Math

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Run PlatformIO Build
        run: pio run -e m5stack-cardputer-adv
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalcPuter-Matematica-firmware
          path: |
            .pio/build/m5stack-cardputer-adv/firmware.bin
            .pio/build/m5stack-cardputer-adv/firmware.elf
            
